### ISSUE TITLE
Acesso direto a banco

### ISSUE THREAD

**Issue by jonasscalar** [josuelima/sped_schema#3]
Parabéns pela iniciativa, poderia disponibilizar a forma que você consegue adquirir este script, estamos hoje (novembro/2015) na versão 2.1.5, seria interessante termos o acesso para atualizações também não acha?
Mais uma pergunta, as tabelas do SPED não são relacionadas?
Abraço e obrigado.
Jonas

**Comment by josuelima** [comment]
Ola Jonas,

Quando vc instala o validador da EFD (ou qualquer outro validador da receita) ele sempre instala junto o MySQL, porem o mesmo so eh startado quando o validador esta em execucao.  Dei uma olhada no codigo java pra achar a porta, usuario e senha que eh utilizado no mysql e depois disso eh soh dar um mysqldump para ter todo o schema em SQL gerado pela propria receita (ou seja, vc vai estar utilizando o mesmo esquema que a receita usa). Para Postgresql eu converti a partir da versao mysql.

Alguns campos adicionais estao la por que criei para meu proprio uso. 

Sim, as tabelas sao relacionadas, mas nao costumo escrever o relacionamento a nivel de banco de dados, sempre faco isso a nivel de aplicacao (mais flexibilidade para meus casos de uso), alem de deixar o SQL mais limpo pra quem quiser reutilizar, no caso aqui do repositorio. Alem do mais cada empresa acaba criando relacionamentos de acordo com suas necessidades.

Eu recomendo vc utilizar um esquema de ID_PAI para os relacionamentos, onde vc atribui a cada registro qual o ID do registro pai (por exemplo C170 -> C100). Dessa forma vc nao precisa criar relacionamentos envolvendo diversas colunas.

Ja nao trabalho mais com nada relacionado a Receita pois me mudei do Brasil, porem fique a vontade para mandar atualizacoes para novas versoes. Acho que nao poderei atualizar os schemas com uma boa frequencia.

**Comment by jonasscalar** [comment]
Obrigado pela resposta super rápida. Estou pensando em conseguir o schema sim. Haviam algumas informações sobre como acessar o banco MYSQL somo usuário e senha, mas ai com as versões mais novas não funciona mais, se tu pudesse me disponibilizar onde e como que tu conseguiu isso no código java já ajuda bastante, isso por que já dei uma olhada também no código java mas não consegui achar o usuário e senha.
Valeu.

**Comment by josuelima** [comment]
Eu tive que fuçar um bocado ate achar.. mas n me lembro mais onde exatamente achei, lembro que o usuario era root e a senha toor

O resto acho que da pra descobrir pela linha de comando (porta). Se vc estiver no linux um `ps aux` vai te mostrar.
